In [ ]:
#Q1.Create a Python program to demonstrate operations/methods of Numpy library on any set of data or array.

In [13]:
import numpy as np
array=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("1.Sum of all elements in the array : ",np.sum(array))
print("2.Mean of the array : ",np.mean(array))
print("3.Median of the array : ",np.median(array))
print("4.Shape  of the array : ",np.shape(array))
print("5.Reshaping  of the array : ",np.reshape(array,(1,9)))
print("6.Transpose of the array : ",np.transpose(array))
print("7.Adding 5 to each element : ",array+5)
print("8.Multiplying 2 to each element : ",array*2)
print("9.Sorting array : ",np.sort(array))
print("10.Maximum value from the array : ",np.max(array))
print("11.Minimum value from the array : ",np.min(array))
print("12.STD Dev value from the array : ",np.std(array))
print("13.Variance value from the array : ",np.var(array))

1.Sum of all elements in the array :  450
2.Mean of the array :  50.0
3.Median of the array :  50.0
4.Shape  of the array :  (3, 3)
5.Reshaping  of the array :  [[10 20 30 40 50 60 70 80 90]]
6.Transpose of the array :  [[10 40 70]
 [20 50 80]
 [30 60 90]]
7.Adding 5 to each element :  [[15 25 35]
 [45 55 65]
 [75 85 95]]
8.Multiplying 2 to each element :  [[ 20  40  60]
 [ 80 100 120]
 [140 160 180]]
9.Sorting array :  [[10 20 30]
 [40 50 60]
 [70 80 90]]
10.Maximum value from the array :  90
11.Minimum value from the array :  10
12.STD Dev value from the array :  25.81988897471611
13.Variance value from the array :  666.6666666666666

#Q2.Create a Python program to create data frame using dictionary which contains columns like, 
ID, Name, Age, &amp; Salary of 15 employees. Perform all statistical operation/methods on to it.

In [37]:
import pandas as pd

# Create a dictionary with employee data
data = {
    'ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah', 'Ivy', 'Jack', 
             'Kathy', 'Leo', 'Mona', 'Nina', 'Oscar'],
    'Age': [25, 30, 22, 35, 40, 28, 24, 27, 31, 36, 29, 33, 38, 26, 32],
    'Salary': [50000, 60000, 55000, 70000, 75000, 62000, 48000, 58000, 54000, 69000,
               56000, 64000, 67000, 55000, 71000]
}

# Create a DataFrame from the dictionary
df = pd.DataFrame(data)

# Display the DataFrame
print("Data Frame:")
print(df)

# Statistical operations
print("\nStatistical Operations:")
print("Mean of Age:", df['Age'].mean())
print("Mean of Salary:", df['Salary'].mean())

print("\nMedian of Age:", df['Age'].median())
print("Median of Salary:", df['Salary'].median())

print("\nStandard Deviation of Age:", df['Age'].std())
print("Standard Deviation of Salary:", df['Salary'].std())

print("\nMinimum Age:", df['Age'].min())
print("Maximum Age:", df['Age'].max())
print("Minimum Salary:", df['Salary'].min())
print("Maximum Salary:", df['Salary'].max())

print("\nSum of Ages:", df['Age'].sum())
print("Sum of Salaries:", df['Salary'].sum())

print("\nCount of Employees:", df['ID'].count())

print("\nSummary :",df[['Age','Salary']].describe())

Data Frame:
    ID     Name  Age  Salary
0    1    Alice   25   50000
1    2      Bob   30   60000
2    3  Charlie   22   55000
3    4    David   35   70000
4    5      Eva   40   75000
5    6    Frank   28   62000
6    7    Grace   24   48000
7    8   Hannah   27   58000
8    9      Ivy   31   54000
9   10     Jack   36   69000
10  11    Kathy   29   56000
11  12      Leo   33   64000
12  13     Mona   38   67000
13  14     Nina   26   55000
14  15    Oscar   32   71000

Statistical Operations:
Mean of Age: 30.4
Mean of Salary: 60933.333333333336

Median of Age: 30.0
Median of Salary: 60000.0

Standard Deviation of Age: 5.288802186831019
Standard Deviation of Salary: 8163.21598624557

Minimum Age: 22
Maximum Age: 40
Minimum Salary: 48000
Maximum Salary: 75000

Sum of Ages: 456
Sum of Salaries: 914000

Count of Employees: 15

Summary :              Age        Salary
count  15.000000     15.000000
mean   30.400000  60933.333333
std     5.288802   8163.215986
min    22.000000  48000.000000
25%    26.500000  55000.000000
50%    30.000000  60000.000000
75%    34.000000  68000.000000
max    40.000000  75000.000000

#Q3. Create a Python program to demonstrate how we can perform indexing and slicing operation on Student.csv file.

In [63]:
import pandas as pd
df=pd.read_csv("Student.csv")
print(df)

#Indexing using loc
print("\n Indexing using loc\n",df.loc[1:2])

#Indexing using iloc
print("\n Indexing using iloc\n",df.iloc[1:3,2:])

#Slicing row
print("\n Slicing row\n",df[1:5])

#Slicing columns using name
print("\n Slicing columns using name\n",df[['Name','Marks']])

#Slicing columns by postions
print("\n Slicing columns by positions\n",df.iloc[:,1:4])

#Condition Sclicing
print("\n Details of Student whoes marks are greater then 80 \n",df[df['Marks']<80])

   ID     Name  Age  Marks Grade
0   1    Alice   20     85     A
1   2      Bob   21     90     A
2   3  Charlie   19     88    B+
3   4    David   22     75     B
4   5      Eva   20     95    A+

 Indexing using loc
    ID     Name  Age  Marks Grade
1   2      Bob   21     90     A
2   3  Charlie   19     88    B+

 Indexing using iloc
    Age  Marks Grade
1   21     90     A
2   19     88    B+

 Slicing row
    ID     Name  Age  Marks Grade
1   2      Bob   21     90     A
2   3  Charlie   19     88    B+
3   4    David   22     75     B
4   5      Eva   20     95    A+

 Slicing columns using name
       Name  Marks
0    Alice     85
1      Bob     90
2  Charlie     88
3    David     75
4      Eva     95

 Slicing columns by positions
       Name  Age  Marks
0    Alice   20     85
1      Bob   21     90
2  Charlie   19     88
3    David   22     75
4      Eva   20     95

 Details of Student whoes marks are greater then 80
    ID   Name  Age  Marks Grade
3   4  David   22     75     B